# Generated by Django 4.2.5 on 2023-10-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('basefare_o', models.SmallIntegerField()),
                ('basefare_i', models.SmallIntegerField()),
                ('add_charge_o', models.SmallIntegerField()),
                ('add_charge_i', models.SmallIntegerField()),
                ('base_d_i', models.SmallIntegerField()),
                ('base_d_o', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JoinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('regno', models.CharField(max_length=12)),
                ('modeltype', models.CharField(max_length=30)),
                ('reqdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=10)),
                ('pickupdate', models.DateField()),
                ('pickuptime', models.TimeField()),
                ('pickup', models.TextField()),
                ('dropoff', models.TextField()),
                ('twoway', models.BooleanField(default=False)),
                ('bookingdate', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('efare', models.IntegerField()),
                ('otp', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='home.cars')),
            ],
        ),
    ]
