# Generated by Django 4.2.5 on 2023-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_joindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='email',
            field=models.EmailField(default='2023-10-05', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
