# Generated by Django 4.2.5 on 2023-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookingdetails_email_bookingdetails_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='otp',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
