# Generated by Django 4.2.5 on 2023-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_joindetail_modelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('basefare_o', models.IntegerField()),
                ('basefare_i', models.IntegerField()),
                ('add_charge_o', models.IntegerField()),
                ('add_charge_i', models.IntegerField()),
            ],
        ),
    ]
