# Generated by Django 4.2.5 on 2023-10-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='base_d',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
