# Generated by Django 4.2.5 on 2023-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_cars_base_d_cars_base_d_i_cars_base_d_o_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='ride',
            field=models.CharField(max_length=3),
        ),
    ]
