# Generated by Django 4.2.5 on 2023-10-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_bookingdetails_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='efare',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
