# Generated by Django 4.2.5 on 2023-10-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bookingdetails_efare'),
    ]

    operations = [
        migrations.AddField(
            model_name='joindetail',
            name='modeltype',
            field=models.CharField(default='AAA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joindetail',
            name='regno',
            field=models.CharField(default='2233DDGG', max_length=12),
            preserve_default=False,
        ),
    ]
